
[drive]
# <- REPLACE THIS with your verified parent folder id
parent_folder_id = "1weWA2nlC2SWH0dVciQp05UWd2n74A288"
registry_name = "_Registry"

# Classes shown in the UI "Select Class"
standard_classes = [ "First Year", "Second Year", "Third Year", "Final Year" ]

[admin]
code = "SGUADMIN"

[grading]
fail_pct = 40
a_pct = 85

[paths]
read_service_account_file = "read.json"  # fallback
read_service_account_files = ["read.json","write.json"]


#parent_folder_id = "1weWA2nlC2SWH0dVciQp05UWd2n74A288" 19Rtrz9VltJRCLu_Ei6XmlS2dBhSO4tmU




